name: Witness Workflow

on:
  workflow_dispatch:
    inputs:
      region:
        description: "The region of ec2 instance"
        required: true
        type: string
      instanceID:
        description: "The ec2 instance ID"
        required: true
        type: string

permissions:
  id-token: write

jobs:
  witness:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - name: Setup Python environment
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3
        with:
          python-version: "3.10"

      - name: Witness the instance
        env:
          AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
          AWS_KEY_SECRET: ${{ secrets.AWS_KEY_SECRET }}
        run: |
          pip install -r requirements.txt
          python main.py "${{ github.event.inputs.region }}" "${{ github.event.inputs.instanceID }}"

      - name: Upload proof as artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          name: ${{ github.event.inputs.instanceID }}-deploy-provenance.json
          path: ${{ github.event.inputs.instanceID }}-deploy-provenance.json
